src/Entity/User.php
<?php
// php bin/console doctrine:schema:update --force
// php bin/console security:encode-password belapass
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity
 * @ORM\Table(name="users");
 */
class User implements UserInterface
{
    /**
     * @var int
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id = 0;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $firstName = "";

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $lastName = "";

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $email = "";

    /**
     * @var string The HASHED password
     * @ORM\Column(type="string", length=1000, nullable=false)
     */
    private $password = "";

    /**
     * @var string[]
     * @ORM\Column(type="json")
     */
    private $roles = array();

    public function __toString()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    // ALT+INS getters+setters, remove setId()
    // Implement remaining UserInterface methods, include phpdoc

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getFirstName(): string
    {
        return $this->firstName;
    }

    /**
     * @param string $firstName
     */
    public function setFirstName(string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * @return string
     */
    public function getLastName(): string
    {
        return $this->lastName;
    }

    /**
     * @param string $lastName
     */
    public function setLastName(string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * @return string
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * @return string
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * @param string $password
     */
    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    /**
     * @return string[]
     */
    public function getRoles(): array
    {
        return $this->roles;
    }

    /**
     * @param string[] $roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    /**
     * @inheritDoc
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * @inheritDoc
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
    }
}

src/Controller/SecurityController.php
<?php
namespace App\Controller;

// https://symfony.com/doc/current/security.html
// https://symfony.com/doc/current/security/form_login_setup.html
// https://symfony.com/doc/4.4/security/guard_authentication.html
// https://ourcodeworld.com/articles/read/1057/how-to-implement-your-own-user-authentication-system-in-symfony-4-3-part-1-creating-a-custom-user-class
// Friends Of Symfony
// https://github.com/FriendsOfSymfony/FOSUserBundle

use App\DTO\LoginDto;
use App\DTO\RegistrationDto;
use App\DTO\UserQueryDto;
use App\Service\SecurityService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    /** @var SecurityService */
    private $security;
    /** @var FormFactoryInterface */
    private $formFactory;

    public function __construct(SecurityService $securityService, FormFactoryInterface $formFactory)
    {
        $this->security = $securityService;
        $this->formFactory = $formFactory;
    }

    /**
     * @param Request $request
     * @return Response
     * @Route(name="app_register", path="/register")
     */
    public function registerAction(Request $request) : Response
    {
        $dto = new RegistrationDto($this->formFactory, $request);
        $form = $dto->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $this->security->registerUser($dto->getEmail(), $dto->getClearPassword(), $dto->getFirstName(), $dto->getLastName());
            $this->addFlash('notice', "{$dto->getEmail()} REGISTERED SUCCESSFULLY");
            return $this->redirectToRoute('app_register');
        }
        return $this->render('security/register.html.twig', ['form'=>$form->createView()]);
    }
    /**
     * @param Request $request
     * @param AuthenticationUtils $authenticationUtils
     * @return Response
     * @Route(name="app_login", path="/login")
     */
    public function loginAction(Request $request, AuthenticationUtils $authenticationUtils) : Response
    {
        $dto = new LoginDto($this->formFactory, $request);
        $dto->setUserName($authenticationUtils->getLastUsername());
        return $this->render('security/login.html.twig', [
           'form' => $dto->getForm()->createView(),
            'myUser' => $this->getUser(),
            'authError'=>$authenticationUtils->getLastAuthenticationError()
        ]);
        // NO $dto->getForm()->handleRequest() => Done by the guard authenticator component!!!
        // access User in any other service: add the CORE Security as DI, Security->getUser
    }

    /**
     * @param Request $request
     * @return Response
     * @Route(name="app_logout", path="/logout")
     */
    public function logoutAction(Request $request) : Response
    {
        // Never actually executed => Logout will be done by the framework!!
    }
    /**
     * @param Request $request
     * @return Response
     * @Route(name="protected_content", path="/protected")
     */
    public function protectedAction(Request $request) : Response
    {
        // if ($this->isGranted("ROLE_ADMIN"))
        $this->denyAccessUnlessGranted("ROLE_ADMIN");
        return new Response("Something TOP SECRET...");
    }

}

templates/security/login.html.twig
{# TODO: should use a VM ... And translate the error message #}
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
    <style>{{ source('css/planes.css') }}</style>
    {% if authError %}
        <p style="color:red; font-weight: bold">LOGIN ERROR: {{ authError.message }}</p>
    {% endif %}

    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
        <p>LOGGED IN!!!</p>
        {% if is_granted("ROLE_ADMIN") %}
            <p>YOU ARE A HIGH LEVEL ADMINISTRATOR...</p>
        {% endif %}

        <p>User entity in Twig: {{ app.user  }}</p>
        <p>User entity from the controller: {{ myUser.username  }}</p>

        <p><a href="{{ path("app_logout") }}">LOG OUT</a></p>
        <p><a href="{{ path("readlist") }}">VIEW AVAILABLE FLIGHTS</a></p>
        <p><a href="{{ path("planelist") }}">ADMIN  ONLY</a></p>
    {% else %}
        <p>NOT LOGGED IN!!!</p>
        {% if form is not null and form is not empty %}
            <div style="width: 400px;padding: 20px">
                {% form_theme form 'bootstrap_4_layout.html.twig' %}
                {{ form_start(form) }}
                {{ form_widget(form) }}
                {{ form_end(form) }}
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

templates/security/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Please Register!{% endblock %}

{% block body %}
    <style>{{ source('css/planes.css') }}</style>
    {% if form is not null and form is not empty %}
        <div style="width: 400px;padding: 20px">
        {% form_theme form 'bootstrap_4_layout.html.twig' %}
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
        </div>
    {% endif %}
{% endblock %}